### ISSUE TITLE
BCM21 driver failure

### ISSUE THREAD

**Issue by riggaroo** [Nilhcem/1602A-androidthings#1]
Hi @Nilhcem 🤓 
I have tried to run this sample on my LCD - have managed to plug everything in. I am getting an exception when trying to run it though and I was wondering if you might be able to help. 
 
I've double checked the circuit setup - also changed the devpreview to version 2 in app build.gradle. Do you maybe have an idea what I'm doing wrong? Have you been able to use the LCD on version 2?
Thanks! 

```
com.nilhcem.androidthings.driver.lcd1602a E/SampleActivity: Error initializing LCD
                                                                                           com.google.android.things.pio.PioException: android.os.ServiceSpecificException: BCM21 driver failure
                                                                                               at com.google.android.things.pio.GpioImpl.setDirection(GpioImpl.java:64)
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.Lcd1602.<init>(Lcd1602.java:119)
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.Lcd1602.<init>(Lcd1602.java:77)
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.SampleActivity.onCreate(SampleActivity.java:27)
                                                                                               at android.app.Activity.performCreate(Activity.java:6662)
                                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                            Caused by: android.os.ServiceSpecificException: BCM21 driver failure
                                                                                               at android.os.Parcel.readException(Parcel.java:1697)
                                                                                               at android.os.Parcel.readException(Parcel.java:1636)
                                                                                               at com.google.android.things.pio.IPeripheralManagerClient$Stub$Proxy.SetGpioDirection(IPeripheralManagerClient.java:969)
                                                                                               at com.google.android.things.pio.GpioImpl.setDirection(GpioImpl.java:62)
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.Lcd1602.<init>(Lcd1602.java:119) 
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.Lcd1602.<init>(Lcd1602.java:77) 
                                                                                               at com.nilhcem.androidthings.driver.lcd1602a.SampleActivity.onCreate(SampleActivity.java:27) 
                                                                                               at android.app.Activity.performCreate(Activity.java:6662) 
                                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

```

**Comment by Nilhcem** [comment]
Hi @riggaroo 

Sorry, but I have no clue :(

I just tried now, cloning this project both on 0.1-devpreview and 0.2-devpreview and it works on both.
Photo here, respecting the cables colors with the schematic from the readme
https://goo.gl/photos/WQEwaTvAYRzCzt4a8

Your error log is mentioning the `BCM21` which is the white cable in the `README.md` schematic. Maybe you can try another cable and another GPIO port (e.g. BCM6 instead, replacing in the SampleActivity.java BCM21 to BCM6) but I'm sure you already tried something similar. Also I would reinstall completely androidthings 0.2-devpreview to make sure.

What I would do if I have this error is actually make the screen work on Arduino, as the platform and library are "stable" and once it works there, try it on Android Things. If it works on the Arduino, then you know at least that issue is not from the cables/hardware but probably the Android Things driver/platform.

Here is the arduino code, to display text on the `1602A` screen module using LiquidCrystal library (plugging the wires on arduino 7, 8, 9, 10, 11, 12)

```c
#include <LiquidCrystal.h>

LiquidCrystal lcd(7, 8, 9, 10, 11, 12);

void setup() {
  lcd.begin(16, 2);
}

void loop() {
  lcd.setCursor(0, 0);
  lcd.print("0123456789ABCDEF");
  lcd.setCursor(0, 1);
  lcd.print("FEDCBA09876543210");
}
```

**Comment by riggaroo** [comment]
After redoing all the wiring on a different breadboard, it is working now. 
*sigh - electronics! 😝 *

Thanks for the help, and for the driver 👍
